tagline: 'Do&nbsp;cool&nbsp;stuff and meet&nbsp;friendly&nbsp;people today in&nbsp;San&nbsp;Francisco.'

what_filters:
  zen:
    label: 'Zen / relaxation'
  sports:
    label: 'Sports'
  outdoor:
    label: 'Outdoor stuff'
  discovery:
    label: 'Discovery / unusual stuff'
  exhibition:
    label: 'Museum / exhibition / culture'
  helpful:
    label: 'Being helpful'
  healthy:
    label: 'Doing healthy stuff'
  music:
    label: 'Watching / playing music'
  performance:
    label: 'Watching a performance'
  movie:
    label: 'Watching a movie'
  tech_hackaton:
    label: 'Technical meetup / hackaton'
  workplace:
    label: 'Come to my workplace!'
  games:
    label: 'Playing games'
  party:
    label: 'Dancing / partying'
  restaurant:
    label: 'Eating / Dining'

where_filters:
  downtown:
    label: 'Downtown'
  soma:
    label: 'South of Market'
  mission:
    label: 'Mission District'
  castro:
    label: 'The Castro'
  financialdistrict:
    label: 'Financial District'
  goldengatepark:
    label: 'Golden Gate Park'
  fishermanswharf:
    label: "Fisherman's Wharf"
  northbeach:
    label: 'North Beach'
  russianhill:
    label: 'Russian Hill'
  chinatown:
    label: 'Chinatown'
  nobhill:
    label: 'Nob Hill'
  port:
    label: 'Port'
  marina:
    label: 'Marina'
  pacificheights:
    label: 'Pacific Heights'
  westernaddition:
    label: 'Western Addition'
  haight:
    label: 'Haight'
  potrerohill:
    label: 'Potrero Hill'
  bernalheights:
    label: 'Bernal Heights'
  noevalley:
    label: 'Noe Valley'
  presidio:
    label: 'Presidio'
  richmond:
    label: 'Richmond district'
  sunset:
    label: 'Sunset district'
  twinpeaks:
    label: 'Twin Peaks'
  excelsior:
    label: 'Excelsior'
  hunterspoint:
    label: "Hunter's point"
  ingleside:
    label: 'Ingleside'
  lakemerced:
    label: 'Lake Merced'